USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/kyocera/202k/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm8960
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := krait
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := 202k

ENABLE_LOKI_RECOVERY := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_RECOVERY_FSTAB := device/kyocera/202k/root/fstab.qcom
BOARD_CUSTOM_GRAPHICS := ../../../device/kyocera/202k/recovery/graphics.c ../../../device/kyocera/202k/recovery/graphics_overlay.c
TARGET_USERIMAGES_USE_EXT4 := true

TARGET_SPECIFIC_HEADER_PATH := device/kyocera/202k/include
BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 no_console_suspend=1 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 maxcpus=2
BOARD_KERNEL_BASE := 0x80200000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x02000000
BOARD_WANTS_EMMC_BOOT := true

TARGET_KERNEL_CONFIG := msm8960_defconfig
TARGET_KERNEL_SOURCE := kernel/kyocera/msm8960

EXTRA_KERNEL_MODULES:
	make -C device/kyocera/202k/mmc_protect KDIR=$(KERNEL_OUT) PWD=$(PWD)/device/kyocera/202k/mmc_protect ARCH=$(TARGET_ARCH) $(ARM_CROSS_COMPILE)
	cp device/kyocera/202k/mmc_protect/mmc_protect.ko $(KERNEL_MODULES_OUT)
	cp device/kyocera/202k/mmc_protect/mmc_protect.ko $(TARGET_RECOVERY_ROOT_OUT)/sbin
TARGET_KERNEL_MODULES := EXTRA_KERNEL_MODULES

BOARD_EGL_CFG := device/kyocera/202k/configs/egl.cfg
BOARD_USES_QCOM_HARDWARE := true
BOARD_USE_MHEAP_SCREENSHOT := true
TARGET_QCOM_DISPLAY_VARIANT := caf
TARGET_USES_C2D_COMPOSITION := true
TARGET_DISPLAY_INSECURE_MM_HEAP := true
TARGET_USES_ION := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
USE_OPENGL_RENDERER := true
TARGET_USES_QCOM_BSP := true
COMMON_GLOBAL_CFLAGS += -DQCOM_BSP -DQCOM_HARDWARE -DUSE_ION

BOARD_USES_ALSA_AUDIO := true
BOARD_USES_LEGACY_ALSA_AUDIO := true
TARGET_USES_QCOM_COMPRESSED_AUDIO := true
COMMON_GLOBAL_CFLAGS += -DQCOM_DIRECTTRACK
TARGET_QCOM_AUDIO_VARIANT := caf
#TARGET_QCOM_MEDIA_VARIANT := caf

BOARD_RIL_CLASS := ../../../device/kyocera/202k/ril/

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00800000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00800000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 973078528
BOARD_USERDATAIMAGE_PARTITION_SIZE := 4370464768
BOARD_FLASH_BLOCK_SIZE := 131072

BOARD_HAS_NO_SELECT_BUTTON := true

BOARD_HAS_QCOM_WLAN := true
BOARD_WLAN_DEVICE := qcwcn
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
TARGET_USES_WCNSS_CTRL := true
TARGET_USES_QCOM_WCNSS_QMI := true
WIFI_DRIVER_MODULE_PATH := "/system/lib/modules/wlan.ko"
WIFI_DRIVER_MODULE_NAME := "wlan"
WPA_SUPPLICANT_VERSION := VER_0_8_X
